import type { TowerStats } from "../types/game";

export const towerConfig: Record<TowerStats["type"], TowerStats> = {
  cannon: {
    type: "cannon",
    label: "狙击塔",
    description: "高物理单体输出，升级后专门打硬目标。",
    color: 0xffc857,
    cost: 70,
    attackType: "physical",
    levels: [
      {
        level: 1,
        upgradeCost: 60,
        attackRange: 4.8,
        attackSpeed: 0.8,
        damage: 34,
        projectileSpeed: 12,
      },
      {
        level: 2,
        upgradeCost: 90,
        attackRange: 5.3,
        attackSpeed: 0.95,
        damage: 52,
        projectileSpeed: 14,
      },
      {
        level: 3,
        attackRange: 5.8,
        attackSpeed: 1.1,
        damage: 74,
        projectileSpeed: 16,
      },
    ],
  },
  mortar: {
    type: "mortar",
    label: "迫击炮塔",
    description: "魔法爆炸范围伤害，适合清群。",
    color: 0xff8c42,
    cost: 110,
    attackType: "magic",
    levels: [
      {
        level: 1,
        upgradeCost: 80,
        attackRange: 4.2,
        attackSpeed: 0.55,
        damage: 22,
        projectileSpeed: 9,
        splashRadius: 1.6,
      },
      {
        level: 2,
        upgradeCost: 110,
        attackRange: 4.6,
        attackSpeed: 0.68,
        damage: 34,
        projectileSpeed: 10,
        splashRadius: 2,
      },
      {
        level: 3,
        attackRange: 5,
        attackSpeed: 0.8,
        damage: 48,
        projectileSpeed: 11,
        splashRadius: 2.3,
      },
    ],
  },
  frost: {
    type: "frost",
    label: "冰霜塔",
    description: "魔法减速塔，升级后控制更稳定。",
    color: 0x72ddf7,
    cost: 90,
    attackType: "magic",
    levels: [
      {
        level: 1,
        upgradeCost: 70,
        attackRange: 4.4,
        attackSpeed: 1.1,
        damage: 10,
        projectileSpeed: 11,
        slowMultiplier: 0.45,
        slowDuration: 1.8,
      },
      {
        level: 2,
        upgradeCost: 100,
        attackRange: 4.8,
        attackSpeed: 1.3,
        damage: 16,
        projectileSpeed: 12,
        slowMultiplier: 0.35,
        slowDuration: 2.2,
      },
      {
        level: 3,
        attackRange: 5.2,
        attackSpeed: 1.5,
        damage: 24,
        projectileSpeed: 13,
        slowMultiplier: 0.28,
        slowDuration: 2.6,
      },
    ],
  },
};
